### ISSUE TITLE
Unify this repo and the older repo

### ISSUE THREAD

**Issue by bsansouci** [gabrielperales/reasonml-koans#1]
Hey @gabrielperales thanks a lot for contributing to tutorials for newcomers. Really appreciate it. 
That being said, could you and @bassjacob coordinate so that we only have 1 repo? Maybe merge this one into the old one, or if @bassjacob doesn’t want to maintain his repo, close it and make this one the primary one.

**Comment by gabrielperales** [comment]
@bsansouci it makes sense, but I started as a new repo because I had to change everything. If he agrees to merge it, I'll do it.

**Comment by bassjacob** [comment]
Unifying it sounds great. I'm not going to be all that active for a while, so more than happy to drop my repo and make @gabrielperales the official one
